name: Build Docker Image

on:
  push:
    branches-ignore: main

jobs:
  build_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Load Environment
        id: dotenv
        uses: falti/dotenv-action@v1

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          build-args: |
            TAG:${{ steps.dotenv.outputs.tag }}
          platforms: "linux/arm64,linux/amd64"
