name: Build Docker Image

on:
  push:
    branches-ignore: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Load Environment
        id: dotenv
        uses: falti/dotenv-action@v1
        with:
          log-variables: true

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            TAG=${{ steps.dotenv.outputs.tag }}
          platforms: "linux/arm64,linux/amd64"
