name: Check For Ginkgo Releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,6,12,18 * * *'

env:
  OWNER: onsi
  REPO: ginkgo

permissions:
  contents: write
  pull-requests: write

jobs:
  check_for_release:
    name: Check For Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Fetch Latest Release
        id: get_latest_release
        uses: octokit/request-action@v2.3.1
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: ${{ env.OWNER }}
          repo: ${{ env.REPO }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with:
          tag: ${{ fromJson(steps.get_latest_release.outputs.data).tag_name }}

      - name: Write .env File
        if: steps.check-tag.outputs.exists == 'false'
        run: |
          TAG="${{ fromJson(steps.get_latest_release.outputs.data).tag_name }}"
          echo "TAG=${TAG}" > .env
          echo "" >> .env

      - name: Create Pull Request
        if: steps.check-tag.outputs.exists == 'false'
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          add-paths: .env
          commit-message: updating to version ${{ fromJson(steps.get_latest_release.outputs.data).tag_name }}
          branch: update-version
          title: Update ${{ env.REPO }} to ${{ fromJson(steps.get_latest_release.outputs.data).tag_name }}
          body: ${{ fromJson(steps.get_latest_release.outputs.data).body }}
          assignees: rogueserenity
